version: '3'

services: 

  app:
    build: 
      context: node
    entrypoint: wait-for db:3306 -t 40 -- ./start.sh
    container_name: app
    networks: 
      - node-network
    tty: true
    depends_on: 
       - db

  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    environment: 
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    networks: 
      - node-network
    
  nginx:
    restart: always
    container_name: nginx
    build:
      context: ./nginx
    entrypoint: wait-for app:3000 -t 60 -- ./start.sh
    networks: 
      - node-network
    ports:
      - "8080:80"
    depends_on: 
      - app

networks: 
  node-network:
    driver: bridge      
